file :mruby do
  sh "git clone --depth=1 git://github.com/mruby/mruby.git"
  Dir.chdir 'mruby' do
    sh "git fetch --tags"
    rev = %x{git rev-parse 2.1.1}
    sh "git checkout #{rev}"
  end
end

MRUBY_CONFIG = File.expand_path("apache_build_config.rb")
desc "compile binary"
task :compile_mruby => :mruby do
  sh "cd mruby && rake all MRUBY_CONFIG=#{MRUBY_CONFIG}"
end

file "mruby/build/host/lib/libmruby.a" => :compile_mruby

files = Dir.glob("./*.c")
files.each {|f| file f }

libs = %w(crypto mruby m readline pthread rt).map {|l| "-l#{l}" }
wc = '-std=c99' # -Wall -Werror-implicit-function-declaration -g'
wl = '' #'-lcrypto -lm '
file '.libs/mod_minimruby.so' =>
     ["mruby/build/host/lib/libmruby.a", *files] do
  sh "apxs -a -c -I./mruby/include -L./mruby/build/host/lib " +
     libs.join(" ") + " " +
     "-Wc,'#{wc}' " +
     "-Wl,'#{wl} ' " + files.join(' ')
end
task :mod => '.libs/mod_minimruby.so'

task :vermod, [:ver] do |_, args|
  files = Dir.glob("./#{args[:ver]}/*.c")
  sh "apxs -a -c -I./mruby/include -L./mruby/build/host/lib " +
     libs.join(" ") + " " +
     "-Wc,'#{wc}' " +
     "-Wl,'#{wl} ' " + files.join(' ')
end

desc "Install mod_minimruby.so to apache2"
#task :install => '.libs/mod_minimruby.so' do
task :install do
  sh "apxs -i -n minimruby .libs/mod_minimruby.so"
end
